### ISSUE TITLE
List and remove boosters (admin)

### ISSUE THREAD

**Issue by corexti** [leomeinel/gbooster#8]
**Description**
I see that there is a command to give boosters to players (x amount), but no way to see which boosters that player has, or if I as an admin can see which boosters that player has.
Adding a command such as "**/gbooster list**" for self, and/or "**/gbooster list <player>**" to see the boosters of a player.

Another idea is if I accidentally give a player a booster I should also be able to remove it from him. A command to remove would do good.

On side note, I've seen plugins add a clickable **[x]** in chat, now adding this can also help. Or maybe even adding **[+]** and **[-]** to increase/decrease booster quantity for a player.
For example: I list boosters of a player and next to each booster is an **[x]** that can help completely remove boosters, a **[+]** to increase, and a **[-]** to decrease.

**[Quantity] [+][-]** _Booster title and/or multiplier_ **[x]**

**Comment by TamrielNetwork** [comment]
Very good idea! 
Im working on getting some bugs fixed atm and also have to do a lot of work for my own server.
Dont expect that feature to be implemented soon but as soon as I got some time Ill work on it!
Or if someone finds this, maybe he also is interested in making a commit! Ill push any PR to the repo that implements interesting stuff like this!

**Comment by leomeinel** [comment]
Will be implemented soon.

**Comment by leomeinel** [comment]
Implemented by the last commits.
